- src: kamaln7.swapfile
- src: geerlingguy.git
- src: geerlingguy.mysql
- src: geerlingguy.redis
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.composer
- src: geerlingguy.varnish
- src: nickhammond.logrotate
