- src: kamaln7.swapfile
- src: geerlingguy.git
  version: 3.0.0
- src: geerlingguy.mysql
  version: 3.5.1
- src: geerlingguy.drush
  version: 3.3.0
- src: geerlingguy.redis
  version: 1.7.0
- src: geerlingguy.nginx
  version: 3.1.0
- src: geerlingguy.php-versions
  version: 5.0.0
- src: geerlingguy.php
  version: 4.7.0
- src: geerlingguy.composer
  version: 1.9.0
- src: geerlingguy.varnish
  version: 3.3.2
- src: nickhammond.logrotate
