---

- name: Copy Drupal snippets
  copy:
    src: ../assets/drupal.conf
    dest: /etc/nginx/snippets/drupal.conf
    owner: root
    group: root
    mode: 0644

- name: Copy default vhost
  copy:
    src: ../assets/default.conf
    dest: /etc/nginx/sites-available/default.conf
    owner: root
    group: root
    mode: 0644

- name: Enable default vhost
  file:
    src=/etc/nginx/sites-available/default.conf
    dest=/etc/nginx/sites-enabled/000-default.conf
    owner=root
    group=root
    state=link
