---

- hosts: all
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - kamaln7.swapfile
    - geerlingguy.git
    - geerlingguy.mysql
    - geerlingguy.redis
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.varnish
    - geerlingguy.drush
    - nickhammond.logrotate

  tasks:
    - include: tasks/nginxconfig.yml
    - name: Intall moreutils
      package:
        name: moreutils
        state: present
    - name: Intall some packages that does not seem to get automatically installed
      package:
        name:
          - s3cmd
          - unzip
          - php{{php_version}}-mysql
          - php{{php_version}}-redis
        state: present
    - name: Copy Varnish config
      template:
        src: templates/default.vcl.j2
        dest: /etc/varnish/default.vcl
        owner: root
        group: root
        mode: 0644
      notify:
        - restart varnish
    - name: Add path to cron
      cron:
        name: PATH
        env: yes
        value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.composer/vendor/bin"
    - name: Add letsencrypt cron job
      cron:
        name: "letsencrypt renew cron"
        minute: 20
        hour: 2
        job: /usr/bin/letsencrypt renew > /var/log/letsencrypt.log
    - name: Make memory limit unlimited on cli
      lineinfile:
        dest: /etc/php/{{ php_default_version_debian }}/cli/php.ini
        state: present
        regexp: memory_limit
        line: memory_limit = -1
    - name: Append the www-data group to the deploy user
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        append: true
        create_home: false
        groups: www-data
    - name: "Reload nginx on cron"
      cron:
        name: "Reload nginx cron"
        minute: 25
        hour: 2
        job: service nginx reload
    - name: Check if php7.4-fpm Exists
      stat: path=/etc/init.d/php7.4-fpm
      register: service_status_74
    - name: Stop service php7.4-fpm, if started
      when: service_status_74.stat.exists
      notify: restart nginx
      service:
        name: php7.4-fpm
        state: stopped
    - name: Check if php8.0-fpm Exists
      stat: path=/etc/init.d/php8.0-fpm
      register: service_status_80
    - name: Stop service php8.0-fpm, if started
      when: service_status_80.stat.exists
      notify: restart nginx
      service:
        name: php8.0-fpm
        state: stopped
    - name: Check if php8.1-fpm Exists
      stat: path=/etc/init.d/php8.1-fpm
      register: service_status_81
    - name: Stop service php8.1-fpm, if started
      when: service_status_81.stat.exists
      notify: restart nginx
      service:
        name: php8.1-fpm
        state: stopped